## <img src="http://icons.iconarchive.com/icons/cornmanthe3rd/plex/256/Other-python-icon.png" width="40"> New York Flights ‚úàÔ∏è üß≥ üóΩ - Python Vs. SQL


<center>

![](https://i.ibb.co/H2HNLcm/2111-w023-n001-1319-B-p1-1319.jpg)

source image [Image by upklyak on Freepik](https://www.freepik.com/free-vector/plane-fly-blue-sky-with-clouds_21388594.htm#page=3&query=flights%20illustration&position=19&from_view=search&track=ais&uuid=82650d86-0491-4a8c-8ac1-763986dbdfb7")

</center>

---

In this exercise, we will compare the implementation of Pandas and SQL for data queries. We'll explore how to use Pandas in a manner similar to SQL by translating SQL queries into Pandas operations. It's important to note that there are various ways to achieve similar results, and the translation of SQL queries to Pandas will be done by employing some of its core methods.

We'll dive into the **nycflights13** dataset, which contains comprehensive data on `airlines`, `airports`, `weather conditions` and `aircraft` for all flights passing through New York airports in 2013. Through this exercise, we'll not only explore Pandas functionality but also learn to apply fundamental SQL concepts in a Python data manipulation environment. This comparison serves as an initial step to delve into translating SQL queries to Pandas, utilizing the available tools in this versatile and powerful library.
<br>

---

<br>

### Entity-relationship diagram [DER]

> The nycflights13 library exclusively comprises tables with flight data from New York airports in 2023. Below, you can find a high-level representation of an entity-relationship diagram with its five tables.

<center>
<img src="https://i.ibb.co/TYwvDqY/nycflights.png" alt="nycflights" border="0" width="40%">
</center>

## Installation: Setting Up nycflights13


To install the nycflights13 library, you can use the following command:
```!pip install nycflights13```

This library provides datasets containing comprehensive information about flights from New York airports in 2023. Once installed, you can easily access and analyze this flight data using various tools and functionalities provided by the nycflights13 package.

In [4]:
# install package
!pip install nycflights13

Collecting nycflights13
  Downloading nycflights13-0.0.3.tar.gz (8.7 MB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 8.7/8.7 MB 53.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.10/dist-packages (from nycflights13) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.0->nycflights13) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.0->nycflights13) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.0->nycflights13) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=0.24.0->nycflights13) (1.16.0)
Building wheels for collected packages: nycflights13
  Building wheel for nycflights13 (setup.py) ... done
  Created wheel for nycflights13: filename=nycflights13-0.0.3-py3-none-any.whl size=8732721 sha256=4e3fc3081105811b377a271aecc3da581e701e15458dc4491f6a70474bd548e9
  Stored in directory: /root/.cache/pip/wheels/64/14/67/ed3bbff6405d6163cfd64d58169cc9284ce9a80c263e759fbe
Successfully built nycflights13
Installing collected packages: nycflights13
Successfully installed nycflights13-0.0.3

# üü¢ Pandas, NumPy, and nycflights13 for Data Analysis in Python

In the next code snippet, we are importing essential Python libraries for data analysis.
* üìó **Pandas** is a powerful library for data manipulation and analysis,
* üìó **Numpy** provides support for numerical operations
* üìó **Nycflights13** is a specialized library containing datasets related to flights from New York airports in 2023.

In [5]:
import pandas as pd
import numpy as np
import nycflights13 as nyc

In the following lines of code, we are assigning two specific datasets from the nycflights13 library to variables.

In [6]:
flights = nyc.flights
airlines = nyc.airlines

# üü¢ SELECT and FROM Statements
The following SQL query retrieves all columns and rows from the "üõ©Ô∏è flights" table. In Pandas, the equivalent is simply writing the DataFrame name, in this case, "flights." For example:

```sql
  SELECT * FROM flights;
```

In [100]:
flights

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

To select specific columns from a Pandas DataFrame, you can use the following syntax:


```sql
  select
    year,
    month,
    day,
    dep_time,
    flight,
    tailnum,
    origin,
    dest
  from flights;
```

In [13]:
(
    flights
      .filter(['year','month','day','dep_time','flight','tailnum','origin','dest'])
)

        year  month  day  dep_time  flight tailnum origin dest
0       2013      1    1     517.0    1545  N14228    EWR  IAH
1       2013      1    1     533.0    1714  N24211    LGA  IAH
2       2013      1    1     542.0    1141  N619AA    JFK  MIA
3       2013      1    1     544.0     725  N804JB    JFK  BQN
4       2013      1    1     554.0     461  N668DN    LGA  ATL
...      ...    ...  ...       ...     ...     ...    ...  ...
336771  2013      9   30       NaN    3393     NaN    JFK  DCA
336772  2013      9   30       NaN    3525     NaN    LGA  SYR
336773  2013      9   30       NaN    3461  N535MQ    LGA  BNA
336774  2013      9   30       NaN    3572  N511MQ    LGA  CLE
336775  2013      9   30       NaN    3531  N839MQ    LGA  RDU

[336776 rows x 8 columns]

# üü¢ Filtering Operators (WHERE)


To filter all ‚úàÔ∏è flights where the origin is 'JFK' in Pandas, you can use the following code:

```sql
select year, month , day, dep_time, flight, tailnum, origin, dest
from flights
  where origin = 'JFK'
limit 10;

```

In [101]:
(
    flights[['year','month','day','dep_time','flight','tailnum','origin','dest']]
      .query("origin=='JFK'")
      .head(10)
)

    year  month  day  dep_time  flight tailnum origin dest
2   2013      1    1     542.0    1141  N619AA    JFK  MIA
3   2013      1    1     544.0     725  N804JB    JFK  BQN
8   2013      1    1     557.0      79  N593JB    JFK  MCO
10  2013      1    1     558.0      49  N793JB    JFK  PBI
11  2013      1    1     558.0      71  N657JB    JFK  TPA
12  2013      1    1     558.0     194  N29129    JFK  LAX
15  2013      1    1     559.0    1806  N708JB    JFK  BOS
23  2013      1    1     606.0    1743  N3739P    JFK  ATL
26  2013      1    1     611.0     303  N532UA    JFK  SFO
27  2013      1    1     613.0     135  N635JB    JFK  RSW

To achieve the same filtering in Pandas for specific criteria:

* ‚úàÔ∏è Flights departing from JFK, LGA, or EWR.

```sql
select year, month , day, dep_time, flight, tailnum, origin, dest
from flights
  where origin in ( 'JFK', 'LGA', 'EWR' )
limit 10;
```

In [18]:
 (
    flights[['year','month','day','dep_time','flight','tailnum','origin','dest']]
      .query("origin in ['JFK', 'EWR', 'LGA']")
      .head(10)
)

   year  month  day  dep_time  flight tailnum origin dest
0  2013      1    1     517.0    1545  N14228    EWR  IAH
1  2013      1    1     533.0    1714  N24211    LGA  IAH
2  2013      1    1     542.0    1141  N619AA    JFK  MIA
3  2013      1    1     544.0     725  N804JB    JFK  BQN
4  2013      1    1     554.0     461  N668DN    LGA  ATL
5  2013      1    1     554.0    1696  N39463    EWR  ORD
6  2013      1    1     555.0     507  N516JB    EWR  FLL
7  2013      1    1     557.0    5708  N829AS    LGA  IAD
8  2013      1    1     557.0      79  N593JB    JFK  MCO
9  2013      1    1     558.0     301  N3ALAA    LGA  ORD

To achieve the same filtering in Pandas for specific criteria:

* ‚úàÔ∏è Flights departing from JFK, LGA, or EWR.
* ‚úàÔ∏è Flights not destined for Miami (MIA).

```sql
select year, month , day, dep_time, flight, tailnum, origin, dest
from flights  
  where origin in ( 'JFK', 'LGA', 'EWR' ) and dest<>'MIA'
limit 10;
```

In [20]:
(
    flights[['year','month','day','dep_time','flight','tailnum','origin','dest']]
      .query("(origin in ['JFK', 'EWR', 'LGA']) and (dest != 'MIA')")
      .head(10)
)

    year  month  day  dep_time  flight tailnum origin dest
0   2013      1    1     517.0    1545  N14228    EWR  IAH
1   2013      1    1     533.0    1714  N24211    LGA  IAH
3   2013      1    1     544.0     725  N804JB    JFK  BQN
4   2013      1    1     554.0     461  N668DN    LGA  ATL
5   2013      1    1     554.0    1696  N39463    EWR  ORD
6   2013      1    1     555.0     507  N516JB    EWR  FLL
7   2013      1    1     557.0    5708  N829AS    LGA  IAD
8   2013      1    1     557.0      79  N593JB    JFK  MCO
9   2013      1    1     558.0     301  N3ALAA    LGA  ORD
10  2013      1    1     558.0      49  N793JB    JFK  PBI

To achieve the same filtering in Pandas for specific criteria:

* ‚úàÔ∏è Flights departing from JFK, LGA, or EWR.
* ‚úàÔ∏è Flights not destined for Miami (MIA).
* ‚úàÔ∏è Flights with a distance less than or equal to 1000 km.

```sql
select year, month , day, dep_time, flight, tailnum, origin, dest
from flights  
  where origin in ( 'JFK', 'LGA', 'EWR' )
   and dest<>'MIA'
   and distance < = 1000
limit 10;
```

In [99]:
(
    flights[['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour','distance']]
      .query("(origin in ['JFK', 'EWR', 'LGA']) and (dest != 'MIA') and (distance <= 1000)")
      .head(10)
)

,year,month,day,dep_time,flight,tailnum,origin,dest,time_hour,distance
4,2013,1,1,554.0,461,N668DN,LGA,ATL,2013-01-01T11:00:00Z,762
5,2013,1,1,554.0,1696,N39463,EWR,ORD,2013-01-01T10:00:00Z,719
7,2013,1,1,557.0,5708,N829AS,LGA,IAD,2013-01-01T11:00:00Z,229
8,2013,1,1,557.0,79,N593JB,JFK,MCO,2013-01-01T11:00:00Z,944
9,2013,1,1,558.0,301,N3ALAA,LGA,ORD,2013-01-01T11:00:00Z,733
15,2013,1,1,559.0,1806,N708JB,JFK,BOS,2013-01-01T10:00:00Z,187
18,2013,1,1,600.0,4650,N542MQ,LGA,ATL,2013-01-01T11:00:00Z,762
21,2013,1,1,602.0,4401,N730MQ,LGA,DTW,2013-01-01T11:00:00Z,502
23,2013,1,1,606.0,1743,N3739P,JFK,ATL,2013-01-01T11:00:00Z,760
25,2013,1,1,608.0,3768,N9EAMQ,EWR,ORD,2013-01-01T11:00:00Z,719

To achieve the same filtering in Pandas for specific criteria:

* ‚úàÔ∏è Flights departing from JFK, LGA, or EWR.
* ‚úàÔ∏è Flights not destined for Miami (MIA).
* ‚úàÔ∏è Flights with a distance less than or equal to 1000 km.
* ‚úàÔ∏è Flights within the period from September 1, 2013, to September 30, 2013.

<center>
<img src="https://i.ibb.co/xXjLvjJ/period-of-times.png" alt="period-of-times" border="0">
</center>


```sql
select year, month , day, dep_time, flight, tailnum, origin, dest
from flights  
  where origin in ( 'JFK', 'LGA', 'EWR' )
   and dest<>'MIA'
   and distance < = 1000
   and time_hour between '2013-09-01' and '2012-09-30'
limit 10;
```

In [103]:
(
    flights[['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour','distance']]
      .query(
            "(origin in ['JFK', 'EWR', 'LGA'])"
             " and (dest != 'MIA')"
             " and (distance <= 1000)"
             " and ('2013-09-01' <= time_hour <= '2013-09-30')"
         )
      .head(10)
)

,year,month,day,dep_time,flight,tailnum,origin,dest,time_hour,distance
309149,2013,8,31,1958.0,1083,N537JB,JFK,MCO,2013-09-01T00:00:00Z,944
309151,2013,8,31,2005.0,418,N266JB,JFK,BOS,2013-09-01T00:00:00Z,187
309152,2013,8,31,2008.0,3535,N508MQ,JFK,CMH,2013-09-01T00:00:00Z,483
309154,2013,8,31,2025.0,1742,N3BVAA,JFK,BOS,2013-09-01T00:00:00Z,187
309156,2013,8,31,2027.0,3395,N936XJ,JFK,DCA,2013-09-01T00:00:00Z,213
309157,2013,8,31,2028.0,686,N258JB,JFK,ROC,2013-09-01T00:00:00Z,264
309161,2013,8,31,2038.0,105,N621JB,JFK,ORD,2013-09-01T00:00:00Z,740
309162,2013,8,31,2048.0,499,N661JB,LGA,MCO,2013-09-01T01:00:00Z,950
309165,2013,8,31,2055.0,4348,N12201,EWR,CLE,2013-09-01T01:00:00Z,404
309169,2013,8,31,2101.0,3322,N929XJ,JFK,PHL,2013-09-01T00:00:00Z,94

To achieve the same filtering in Pandas for specific criteria:

* ‚úàÔ∏è Flights departing from JFK, LGA, or EWR.
* ‚úàÔ∏è Flights not destined for Miami (MIA).
* ‚úàÔ∏è Flights with a distance less than or equal to 1000 km.
* ‚úàÔ∏è Flights within the period from September 1, 2013, to September 30, 2013.
* ‚úàÔ∏è Flights where the tailnum contains 'N5' in the text.

You can use the following code:

```sql
select year, month , day, dep_time, flight, tailnum, origin, dest
from flights  
  where origin in ( 'JFK', 'LGA', 'EWR' )
   and dest<>'MIA'
   and distance < = 1000
   and time_hour between '2013-09-01' and '2012-09-30'
   and tailnum like '%N5%'
limit 10;
```

In [69]:

(
    flights
      .filter(['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour'])
      .query(
             " (origin in ['JFK', 'EWR', 'LGA'])"
             " and (dest != 'MIA') "
             " and ('2013-09-01' <= time_hour <= '2013-09-30') "
             " and (tailnum.str.find('N5')>=0)"
       )
      .head(10)
)

,year,month,day,dep_time,flight,tailnum,origin,dest,time_hour
309149,2013,8,31,1958.0,1083,N537JB,JFK,MCO,2013-09-01T00:00:00Z
309152,2013,8,31,2008.0,3535,N508MQ,JFK,CMH,2013-09-01T00:00:00Z
309160,2013,8,31,2032.0,1505,N510JB,JFK,ABQ,2013-09-01T00:00:00Z
309163,2013,8,31,2049.0,165,N568JB,JFK,PDX,2013-09-01T00:00:00Z
309167,2013,8,31,2057.0,135,N580JB,JFK,PHX,2013-09-01T00:00:00Z
309168,2013,8,31,2100.0,1103,N595JB,JFK,SJU,2013-09-01T01:00:00Z
309171,2013,8,31,2106.0,523,N523JB,JFK,LAX,2013-09-01T00:00:00Z
309173,2013,8,31,2113.0,1371,N506JB,LGA,FLL,2013-09-01T01:00:00Z
309189,2013,8,31,2214.0,1183,N561JB,JFK,MCO,2013-09-01T01:00:00Z
309204,2013,9,1,508.0,1545,N57869,EWR,IAH,2013-09-01T09:00:00Z

To achieve the same filtering in Pandas for specific criteria:

* ‚úàÔ∏è Flights departing from JFK, LGA, or EWR.
* ‚úàÔ∏è Flights not destined for Miami (MIA).
* ‚úàÔ∏è Flights with a distance less than or equal to 1000 km.
* ‚úàÔ∏è Flights within the period from September 1, 2013, to September 30, 2013.
* ‚úàÔ∏è Flights where the tailnum contains 'N5' in the text.
* ‚úàÔ∏è Flights where dep_time is null

You can use the following code:

```sql
select year, month , day, dep_time, flight, tailnum, origin, dest
from flights  
  where origin in ( 'JFK', 'LGA', 'EWR' )
   and dest<>'MIA'
   and distance < = 1000
   and time_hour between '2013-09-01' and '2012-09-30'
   and tailnum like '%N5%'
   and dep_time is null
limit 10;
```

In [105]:
(
    flights
      .filter(['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour'])
      .query(
             " (origin in ['JFK', 'EWR', 'LGA'])"
             " and (dest != 'MIA') "
             " and ('2013-09-01' <= time_hour <= '2013-09-30') "
             " and (tailnum.str.find('N5')>=0)"
             " and dep_time.isnull()"
       )
      .head(10)
)

,year,month,day,dep_time,flight,tailnum,origin,dest,time_hour
310813,2013,9,2,NaN,335,N596AA,LGA,ORD,2013-09-02T19:00:00Z
310818,2013,9,2,NaN,3134,N508MQ,EWR,ORD,2013-09-02T22:00:00Z
310819,2013,9,2,NaN,3199,N500MQ,LGA,CLT,2013-09-02T19:00:00Z
310821,2013,9,2,NaN,3301,N532MQ,LGA,RDU,2013-09-02T21:00:00Z
310824,2013,9,2,NaN,3384,N505MQ,LGA,CLT,2013-09-03T01:00:00Z
310825,2013,9,2,NaN,3317,N522MQ,LGA,RDU,2013-09-03T01:00:00Z
310827,2013,9,2,NaN,3416,N522MQ,LGA,RDU,2013-09-02T19:00:00Z
310828,2013,9,2,NaN,3556,N506MQ,LGA,DTW,2013-09-02T21:00:00Z
310830,2013,9,2,NaN,3588,N510MQ,LGA,MSP,2013-09-02T18:00:00Z
310832,2013,9,2,NaN,3622,N531MQ,LGA,BNA,2013-09-02T20:00:00Z

# üü¢ Order by Statement

The **.sort_values()** methods in Pandas are equivalent to the ORDER BY clause in SQL.

1. `**.sort_values(['origin','dest'], ascending=False)**`: This method sorts the DataFrame based on the 'origin' and 'dest' columns in descending order (from highest to lowest). In SQL, this would be similar to the **`ORDER BY origin DESC, dest DESC`**  clause.

2. `**.sort_values(['day'], ascending=True)**`: This method sorts the DataFrame based on the 'day' column in ascending order (lowest to highest). In SQL, this would be similar to the **`ORDER BY day ASC `** clause.

Both methods allow you to sort your DataFrame according to one or more columns, specifying the sorting direction with the ascending parameter. True means ascending order, and False means descending order.


```sql
select year, month , day, dep_time, flight, tailnum, origin, dest
from flights  
  where origin in ( 'JFK', 'LGA', 'EWR' )
   and dest<>'MIA'
   and distance < = 1000
   and time_hour between '2013-09-01' and '2012-09-30'
   and tailnum like '%N5%'
   and dep_time is null
order by  origin, dest desc
limit 10;
```

In [107]:

(
    flights
      .filter(['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour'])
      .query(
             " (origin in ['JFK', 'EWR', 'LGA'])"
             " and (dest != 'MIA') "
             " and ('2013-09-01' <= time_hour <= '2013-09-30') "
             " and (tailnum.str.find('N5')>=0)"
             " and year.notnull()"
       )
      .sort_values(['origin','dest'],ascending=False)
      .head(10)

)

,year,month,day,dep_time,flight,tailnum,origin,dest,time_hour
310967,2013,9,3,735.0,1717,N519JB,LGA,TPA,2013-09-03T11:00:00Z
311469,2013,9,3,1618.0,1117,N510JB,LGA,TPA,2013-09-03T20:00:00Z
311930,2013,9,4,740.0,1717,N563JB,LGA,TPA,2013-09-04T11:00:00Z
312893,2013,9,5,749.0,1717,N598JB,LGA,TPA,2013-09-05T11:00:00Z
315453,2013,9,8,731.0,1717,N598JB,LGA,TPA,2013-09-08T11:00:00Z
315910,2013,9,8,1544.0,1117,N583JB,LGA,TPA,2013-09-08T20:00:00Z
316908,2013,9,9,1546.0,1117,N556JB,LGA,TPA,2013-09-09T20:00:00Z
317404,2013,9,10,740.0,1717,N509JB,LGA,TPA,2013-09-10T11:00:00Z
318861,2013,9,11,1607.0,1117,N537JB,LGA,TPA,2013-09-11T20:00:00Z
319751,2013,9,12,1555.0,1117,N584JB,LGA,TPA,2013-09-12T20:00:00Z

# üü¢ Distinct Values: Removing Duplicates from Results

To perform a distinct select in pandas, you need to first execute the entire query, and then apply the `drop_duplicates()` method to eliminate all duplicate rows.

```sql
select distinct origin, dest
from flights  
  where origin in ( 'JFK', 'LGA', 'EWR' )
   and dest<>'MIA'
   and time_hour between '2013-09-01' and '2012-09-30'
order by  origin, dest desc;
```

In [77]:
(
    flights
      .filter(['origin','dest','time_hour'])
      .query(
             " (origin in ['JFK', 'EWR', 'LGA'])"
             " and (dest != 'MIA') "
             " and ('2013-09-01' <= time_hour <= '2013-09-30') "
       )
      .filter(['origin','dest'])
      .drop_duplicates()

)

       origin dest
309149    JFK  MCO
309151    JFK  BOS
309152    JFK  CMH
309153    JFK  TPA
309155    EWR  SFO
...       ...  ...
315604    LGA  IND
316120    LGA  GSP
316644    EWR  SYR
327556    LGA  SBN
334382    EWR  STT

[192 rows x 2 columns]

# üü¢ Adding Calculated Columns
Now, let's introduce a new calculated column called "delay_total," where we sum the values from the "dep_delay" and "arr_delay" columns.

```sql
select  
  origin,
  dest,
  time_hour,
  dep_delay,
  arr_delay,
  flights.dep_delay + flights.arr_delay as delay_total
from flights  
  where origin in ( 'JFK', 'LGA', 'EWR' )
   and dest<>'MIA'
   and time_hour between '2013-09-01' and '2012-09-30';
```

In [81]:
(
    flights
      .filter(['origin','dest','time_hour','dep_delay','arr_delay'])
      .assign(delay_total = flights.dep_delay + flights.arr_delay )
      .query(
             " (origin in ['JFK', 'EWR', 'LGA'])"
             " and (dest != 'MIA') "
             " and ('2013-09-01' <= time_hour <= '2013-09-30') "
       )
)

       origin dest             time_hour  dep_delay  arr_delay  delay_total
309149    JFK  MCO  2013-09-01T00:00:00Z       -3.0       -6.0         -9.0
309151    JFK  BOS  2013-09-01T00:00:00Z       -5.0      -11.0        -16.0
309152    JFK  CMH  2013-09-01T00:00:00Z       -7.0      -20.0        -27.0
309153    JFK  TPA  2013-09-01T00:00:00Z       11.0      -15.0         -4.0
309154    JFK  BOS  2013-09-01T00:00:00Z        0.0       -6.0         -6.0
...       ...  ...                   ...        ...        ...          ...
335717    LGA  ATL  2013-09-29T23:00:00Z       55.0       63.0        118.0
335720    JFK  ROC  2013-09-29T21:00:00Z      199.0      181.0        380.0
335778    LGA  FLL  2013-09-29T23:00:00Z      225.0      183.0        408.0
335781    EWR  ORD  2013-09-29T22:00:00Z        NaN        NaN          NaN
335782    LGA  ORD  2013-09-29T11:00:00Z        NaN        NaN          NaN

[25656 rows x 6 columns]

# üü¢ Group by Statement

To perform a **GROUP BY** operation in pandas, we'll use the groupby method, which operates similarly to its SQL counterpart. Similarly, we can employ common aggregate functions such as sum, max, min, mean (equivalent to avg in SQL), and count. Below is a simple example to illustrate this process:


```sql
select
  year,
  month,
  max(dep_delay) as dep_delay,
  from flights

```

In [24]:
(
    flights
      .groupby(['year','month'],as_index=False)
      ['dep_delay'].max()
)

    year  month  dep_delay
0   2013      1     1301.0
1   2013      2      853.0
2   2013      3      911.0
3   2013      4      960.0
4   2013      5      878.0
5   2013      6     1137.0
6   2013      7     1005.0
7   2013      8      520.0
8   2013      9     1014.0
9   2013     10      702.0
10  2013     11      798.0
11  2013     12      896.0

In the following example, we'll explore how to implement a **HAVING** clause in pandas, leveraging the query method, as we've done previously for filtering.


```sql
select
  year,
  month,
  max(dep_delay) as dep_delay,
  from flights
  having max(dep_delay)>1000

```

In [27]:
(
    flights
      .groupby(['year','month'],as_index=False)['dep_delay']
      .max()
      .query('(dep_delay>1000)') # having
)

   year  month  dep_delay
6  2013      7     1005.0
8  2013      9     1014.0

When working with pandas and needing to perform multiple calculations on the same column or across different columns, the agg function becomes a valuable tool. It allows you to specify a list of calculations to be applied, providing flexibility and efficiency in data analysis.

Consider the following SQL query:



```sql
select
  year,
  month,
  max(dep_delay)  as dep_delay_max,
  min(dep_delay)  as dep_delay_min,
  mean(dep_delay) as dep_delay_mean,
  count(*)        as dep_delay_count,
  max(arr_delay)  as arr_delay_max,
  min(arr_delay)  as arr_delay_min,
  sum(arr_delay)  as arr_delay_sum
from flights


```

> This query retrieves aggregated information from the "flights" dataset, calculating various statistics like maximum, minimum, mean, count, and sum for both "dep_delay" and "arr_delay" columns. To achieve a similar result in pandas, we use the agg function, which allows us to specify these calculations concisely and efficiently. The resulting DataFrame provides a clear summary of the specified metrics for each combination of "year" and "month."

In [39]:
result = (
    flights
      .groupby(['year','month'],as_index=False)
      .agg({'dep_delay':['max','min','mean','count'], 'arr_delay':['max','min','sum']})
)

# Concatenate function names with column names
result.columns = result.columns.map('_'.join)

result.head()

,year_,month_,dep_delay_max,dep_delay_min,dep_delay_mean,dep_delay_count,arr_delay_max,arr_delay_min,arr_delay_sum
0,2013,1,1301.0,-30.0,10.036665,26483,1272.0,-70.0,161819.0
1,2013,2,853.0,-33.0,10.816843,23690,834.0,-70.0,132529.0
2,2013,3,911.0,-25.0,13.227076,27973,915.0,-68.0,162043.0
3,2013,4,960.0,-21.0,13.938038,27662,931.0,-68.0,308057.0
4,2013,5,878.0,-24.0,12.986859,28233,875.0,-86.0,99053.0

# üü¢ Union Statement

To execute a UNION ALL operation in Pandas, it is necessary to create two DataFrames and concatenate them using the concat method. Unlike SQL, a DataFrame in Pandas can be combined to generate additional columns or additional rows. Therefore, it is essential to define how the concatenation should be performed:

* **axis=1** => Union that appends another dataset to the right, generating more columns.
* **axis=0** => Union that appends more rows.

<center>
<img src="https://i.ibb.co/0YfV2Xx/concat.png" alt="concat" border="0">
</center>



In our example, we will perform the equivalent of a UNION ALL in SQL, so we will use axis=0.

```sql
select  
  origin,
  dest,
  time_hour,
  dep_delay,
  arr_delay,
  flights.dep_delay + flights.arr_delay as delay_total ,
  'NYC' group
FROM flights  
  WHERE origin in ( 'JFK', 'LGA', 'EWR' )
   and dest<>'MIA'
   and time_hour between '2013-09-01' and '2012-09-30'
ORDER BY flights.dep_delay + flights.arr_delay DESC
LIMIT 3
UNION ALL
select  
  origin,
  dest,
  time_hour,
  dep_delay,
  arr_delay,
  flights.dep_delay + flights.arr_delay as delay_total ,
  'MIA' group
FROM flights  
  WHERE origin in ( 'JFK', 'LGA', 'EWR' )
   and time_hour between '2013-07-01' and '2012-09-30'
  ORDER BY flights.dep_delay + flights.arr_delay DESC
  LIMIT 2

;
```

In [84]:
Flights_NYC = (
    flights
      .filter(['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour','dep_delay','arr_delay'])
      .assign(delay_total = flights.dep_delay + flights.arr_delay )
      .query(
             " (origin in ['JFK', 'EWR', 'LGA'])"
             " and ('2013-09-01' <= time_hour <= '2013-09-30') "
       )
     .assign(group ='NYC')
     .sort_values('delay_total',ascending=False)
     .head(3)
)

Flights_MIAMI = (
    flights
      .filter(['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour','dep_delay','arr_delay'])
      .assign(delay_total = flights.dep_delay + flights.arr_delay )
      .query(
             " (dest in ['MIA', 'OPF', 'FLL'])"
             " and ('2013-07-01' <= time_hour <= '2013-09-30') "
       )
     .assign(group ='MIA')
     .sort_values('delay_total',ascending=False)
     .head(2)
)


pd.concat([ Flights_NYC,Flights_MIAMI],axis=0)

,year,month,day,dep_time,flight,tailnum,origin,dest,time_hour,dep_delay,arr_delay,delay_total,group
327043,2013,9,20,1139.0,177,N338AA,JFK,SFO,2013-09-20T22:00:00Z,1014.0,1007.0,2021.0,NYC
309955,2013,9,2,606.0,2131,N913DE,LGA,DTW,2013-09-02T22:00:00Z,696.0,674.0,1370.0,NYC
319189,2013,9,12,12.0,350,N956AT,LGA,ATL,2013-09-12T18:00:00Z,602.0,572.0,1174.0,NYC
269754,2013,7,21,1555.0,1895,N3EMAA,EWR,MIA,2013-07-21T10:00:00Z,580.0,645.0,1225.0,MIA
306507,2013,8,28,2315.0,1373,N3763D,JFK,MIA,2013-08-28T19:00:00Z,436.0,399.0,835.0,MIA

# üü¢ CASE WHEN Statement

To replicate the `CASE WHEN` statement, we can use two different methods from NumPy:

1. If there are only two conditions, for example, checking if the total delay exceeds 0, then we label it as "Delayed"; otherwise, we label it as "On Time". For this, the `np.where` method from NumPy is utilized.


```sql
select  
  origin,
  dest,
  time_hour,
  dep_delay,
  arr_delay,
  (case
    when flights.dep_delay + flights.arr_delay >0 then 'Delayed'
    else 'On Time' end) as status ,
FROM flights  
LIMIT 5;
```

<center>
<img src="https://i.ibb.co/9wmNds8/case-when.png" alt="case-when" border="0">
</center>

In [9]:
(
    flights
      .filter(['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour','dep_delay','arr_delay'])
      .assign(status=np.where((flights['dep_delay'] + flights['arr_delay']) > 0, 'Delayed', 'On Time'))
      .head(5)
)

,year,month,day,dep_time,flight,tailnum,origin,dest,time_hour,dep_delay,arr_delay,status
0,2013,1,1,517.0,1545,N14228,EWR,IAH,2013-01-01T10:00:00Z,2.0,11.0,Delayed
1,2013,1,1,533.0,1714,N24211,LGA,IAH,2013-01-01T10:00:00Z,4.0,20.0,Delayed
2,2013,1,1,542.0,1141,N619AA,JFK,MIA,2013-01-01T10:00:00Z,2.0,33.0,Delayed
3,2013,1,1,544.0,725,N804JB,JFK,BQN,2013-01-01T10:00:00Z,-1.0,-18.0,On Time
4,2013,1,1,554.0,461,N668DN,LGA,ATL,2013-01-01T11:00:00Z,-6.0,-25.0,On Time

2. In case there are more conditions, such as identifying Miami airports and labeling them as "MIA", labeling "ATL" airports that they are in Altanta, and for any other cases, using the label "OTHER". For this, the `np.select` method from NumPy is employed.

City | Name | Acronym
-----|------|--------
Miami | Miami International |  (MIA)
Miami | Opa-locka Executive  | (OPF)
Miami | Fort Lauderdale-Hollywood  | (FLL)
Atlanta | Hartsfield-Jackson Atlanta |(ATL)
Atlanta | DeKalb-Peachtree |(PDK)
Atlanta | Fulton County |(FTY)

---


```sql
select  
  origin,
  dest,
  time_hour,
  dep_delay,
  arr_delay,
  (case
    when dest in ('ATL','PDK','FTY') then 'ATL'
    when dest in ('MIA','OPF','FLL') then 'MIA'
    else 'Other'
  end) as city ,
FROM flights  
LIMIT 10;
```

In [17]:
(
    flights
      .filter(['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour','dep_delay','arr_delay'])
      .assign(city=np.select([
                                  flights['dest'].isin(['ATL','PDK','FTY']),
                                  flights['dest'].isin(['MIA', 'OPF', 'FLL']),
                                ],
                               ['ATL','MIA'],
                               default='Other')
      )
    .head(10)
)

,year,month,day,dep_time,flight,tailnum,origin,dest,time_hour,dep_delay,arr_delay,status
0,2013,1,1,517.0,1545,N14228,EWR,IAH,2013-01-01T10:00:00Z,2.0,11.0,Other
1,2013,1,1,533.0,1714,N24211,LGA,IAH,2013-01-01T10:00:00Z,4.0,20.0,Other
2,2013,1,1,542.0,1141,N619AA,JFK,MIA,2013-01-01T10:00:00Z,2.0,33.0,MIA
3,2013,1,1,544.0,725,N804JB,JFK,BQN,2013-01-01T10:00:00Z,-1.0,-18.0,Other
4,2013,1,1,554.0,461,N668DN,LGA,ATL,2013-01-01T11:00:00Z,-6.0,-25.0,ATL
5,2013,1,1,554.0,1696,N39463,EWR,ORD,2013-01-01T10:00:00Z,-4.0,12.0,Other
6,2013,1,1,555.0,507,N516JB,EWR,FLL,2013-01-01T11:00:00Z,-5.0,19.0,MIA
7,2013,1,1,557.0,5708,N829AS,LGA,IAD,2013-01-01T11:00:00Z,-3.0,-14.0,Other
8,2013,1,1,557.0,79,N593JB,JFK,MCO,2013-01-01T11:00:00Z,-3.0,-8.0,Other
9,2013,1,1,558.0,301,N3ALAA,LGA,ORD,2013-01-01T11:00:00Z,-2.0,8.0,Other

# üü¢ JOIN Statement

Entity relationship diagram [DER]

<center>
<img src="https://i.ibb.co/TYwvDqY/nycflights.png" alt="nycflights" border="0" width="40%">
</center>


----

When performing a join in Pandas, the merge method should be used.

## üìó Join Types
How: Specifies the type of join to be performed. Available options: `{'left', 'right', 'outer', 'inner', 'cross'}`

<center>
<img src="https://i.ibb.co/rpMBDHq/joins.png" alt="joins" border="0">
</center>

## üìó Join Key
On: The key on which the tables will be joined. If more than one column is involved, a list should be provided. Examples:

* Single variable: `on='year'`
```python
fligths.merge(planes, how='inner', on='tailnum')
```
* Two variables: on=['year','month','day']
```python
fligths.merge(weather, how='inner', on=['year','month','day'])
```
* left_on/right_on: When the columns have different names, these parameters should be used. For example:
```python
fligths.merge(airports, how='inner', left_on = 'origin', rigth_on='faa')
```

---

Here's an example using the airlines and flights tables:

```sql
select  
  f.year,
  f.month,
  f.day,
  f.dep_time,
  f.flight,
  f.tailnum,
  f.origin as airport_origen,
  f.dest,
  f.time_hour,
  f.dep_delay,
  f.arr_delay,
  f.carrier,
  a.name as airline_name
FROM flights  f
  left join airlines a on f.carrier = a.carrier
LIMIT 5;
```

# üü¢  Rename
> The rename method is used to rename columns, similar to the "as" clause in SQL.

In [20]:
(
    flights
      .filter(['year','month','day','dep_time','flight','tailnum','origin','dest','time_hour','dep_delay','arr_delay','carrier'])
      .merge(airlines, how = 'left', on ='carrier')
      .rename(columns={'name':'airline_name','origin':'airport_origen'})
      .head(5)
)

,year,month,day,dep_time,flight,tailnum,airport_origen,dest,time_hour,dep_delay,arr_delay,carrier,airline_name
0,2013,1,1,517.0,1545,N14228,EWR,IAH,2013-01-01T10:00:00Z,2.0,11.0,UA,United Air Lines Inc.
1,2013,1,1,533.0,1714,N24211,LGA,IAH,2013-01-01T10:00:00Z,4.0,20.0,UA,United Air Lines Inc.
2,2013,1,1,542.0,1141,N619AA,JFK,MIA,2013-01-01T10:00:00Z,2.0,33.0,AA,American Airlines Inc.
3,2013,1,1,544.0,725,N804JB,JFK,BQN,2013-01-01T10:00:00Z,-1.0,-18.0,B6,JetBlue Airways
4,2013,1,1,554.0,461,N668DN,LGA,ATL,2013-01-01T11:00:00Z,-6.0,-25.0,DL,Delta Air Lines Inc.